# Generated by Django 5.0.3 on 2024-03-30 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gymodel',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='gymodel',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 29, 18, 35, 59, 347565, tzinfo=datetime.timezone.utc)),
        ),
    ]
