# Generated by Django 5.0.3 on 2024-03-30 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0002_rename_title_gymodel_name_alter_gymodel_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='gymodel',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gymodel',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gymodel',
            name='phone',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='gymodel',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gymodel',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 29, 18, 57, 30, 306930, tzinfo=datetime.timezone.utc)),
        ),
    ]
