# Generated by Django 5.0.3 on 2024-03-30 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0003_remove_profile_first_name_remove_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymodel',
            name='age',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='gymodel',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 29, 20, 4, 50, 104409, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gymodel',
            name='height',
            field=models.IntegerField(default=150),
        ),
        migrations.AlterField(
            model_name='gymodel',
            name='weight',
            field=models.IntegerField(default=50),
        ),
    ]
