# Generated by Django 5.0.3 on 2024-03-31 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0004_alter_gymodel_age_alter_gymodel_end_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Users',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='users',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='gymodel',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 30, 4, 50, 17, 834318, tzinfo=datetime.timezone.utc)),
        ),
    ]
