# Generated by Django 5.0.3 on 2024-03-31 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0005_rename_profile_users_rename_users_users_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='gymodel',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 30, 4, 52, 53, 618714, tzinfo=datetime.timezone.utc)),
        ),
    ]
