# Generated by Django 5.0.3 on 2024-03-31 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0006_rename_users_user_alter_gymodel_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='gymodel',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 30, 9, 0, 49, 114840, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gymodel',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
