# Generated by Django 5.0.3 on 2024-03-31 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0007_user_status_alter_gymodel_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gymodel',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 30, 9, 22, 12, 699300, tzinfo=datetime.timezone.utc)),
        ),
    ]
