# Generated by Django 5.0.3 on 2024-03-31 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0008_user_name_alter_gymodel_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymodel',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 30, 9, 24, 31, 956108, tzinfo=datetime.timezone.utc)),
        ),
    ]
