# Generated by Django 5.0.3 on 2024-04-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0009_alter_gymodel_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gymodel',
            options={'ordering': ['-start_date']},
        ),
        migrations.AddField(
            model_name='gymodel',
            name='renewal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gymodel',
            name='end_date',
            field=models.CharField(default='1403-02-16', max_length=10),
        ),
        migrations.AlterField(
            model_name='gymodel',
            name='start_date',
            field=models.CharField(default='1403-01-17', max_length=10),
        ),
    ]
