# Generated by Django 5.0.3 on 2024-04-07 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0010_alter_gymodel_options_gymodel_renewal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymodel',
            name='end_date',
            field=models.CharField(default='1403-02-17', max_length=10),
        ),
        migrations.AlterField(
            model_name='gymodel',
            name='start_date',
            field=models.CharField(default='1403-01-18', max_length=10),
        ),
    ]
