# Generated by Django 5.0.3 on 2024-04-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0011_alter_gymodel_end_date_alter_gymodel_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymodel',
            name='previous_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gymodel',
            name='end_date',
            field=models.CharField(default='1403-02-19', max_length=10),
        ),
        migrations.AlterField(
            model_name='gymodel',
            name='start_date',
            field=models.CharField(default='1403-01-20', max_length=10),
        ),
    ]
