# Generated by Django 5.0.3 on 2024-04-12 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0014_remove_gymodel_previous_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymodel',
            name='status_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gymodel',
            name='end_date',
            field=models.CharField(default='1403-02-22', max_length=10),
        ),
        migrations.AlterField(
            model_name='gymodel',
            name='start_date',
            field=models.CharField(default='1403-01-23', max_length=10),
        ),
        migrations.AlterField(
            model_name='gymodel',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
