# Generated by Django 4.2 on 2024-04-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0015_gymodel_status_updated_alter_gymodel_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gymodel',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='gymodel',
            name='status_updated',
        ),
        migrations.AlterField(
            model_name='gymodel',
            name='end_date',
            field=models.CharField(default='1403-02-30', max_length=10),
        ),
        migrations.AlterField(
            model_name='gymodel',
            name='start_date',
            field=models.CharField(default='1403-01-31', max_length=10),
        ),
    ]
