# Generated by Django 4.2 on 2024-04-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0016_alter_gymodel_options_remove_gymodel_status_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymodel',
            name='end_date',
            field=models.CharField(default='1403-02-31', max_length=10),
        ),
        migrations.AlterField(
            model_name='gymodel',
            name='height',
            field=models.FloatField(default=150),
        ),
        migrations.AlterField(
            model_name='gymodel',
            name='start_date',
            field=models.CharField(default='1403-02-01', max_length=10),
        ),
        migrations.AlterField(
            model_name='gymodel',
            name='weight',
            field=models.FloatField(default=50),
        ),
    ]
